version: "3.8"

services:
  visdat-dashboard:
    build:
      context: ./            
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1

    # command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
