version: "3.8"

services:
  visdat-dashboard:
    build:
      context: ./            
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501" # jupyter
      - "8502:8502" # streamlit
    environment:
      - PYTHONUNBUFFERED=1

    # command: 
