version: "3.8"

services:
  visdat-dashboard:
    build:
      context: ./            
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501" # jupyter
      - "8502:8502" # streamlit
    environment:
      - PYTHONUNBUFFERED=1

    command:
      - bash
      - -lc
      - |
        set -e
        # Jupyter
        jupyter notebook \
          --ip=0.0.0.0 \
          --port=8501 \
          --no-browser \
          --allow-root \
          --ServerApp.token= \
          --ServerApp.password= &

        # Streamlit
        exec streamlit run app/src/streamlit/eicu_patient_dashboard.py \
          --server.address=0.0.0.0 \
          --server.port=8502
